export const AD_TEMPLATE_KIND = {
  FROSTED: "frostedPanel",
  PHOTO_BAND: "photoBand",
};

/** Applied on first load and after reset; matches `AD_TEMPLATES` entry below. */
export const DEFAULT_AD_BUILDER_TEMPLATE_ID = "frost-hero-left";

/**
 * Static ad templates.
 *
 * Notes:
 * - Templates are "ready-made" layout + copy starters.
 * - Background image (photo) stays user-driven; we only pre-tune `imageScale`
 *   and offsets so the composition looks intentional once the user picks an image.
 * - We intentionally do NOT touch bgPalette/frostPalette because those are locked
 *   by the selected logo’s brand palette.
 */
export const AD_TEMPLATES = [
  {
    id: "frost-hero-left",
    
    title: "Hero Frost",
    description: "Bold headline with a glass panel over the photo.",
    targetOrientations: ["landscape", "portrait", "square"],
    adLayout: AD_TEMPLATE_KIND.FROSTED,
    photoBandMode: "any",
    patch: {
      adLayout: "frostedPanel",
      frostPanelEnabled: true,
      frostOpacity: 0.55,
      frostPanelScale: 0.86,
      frostPanelOffsetX: 0,
      frostPanelOffsetY: -6,
      headlineFontScale: 1.1,
      subtextFontScale: 1,
      headlineLineHeight: 1.08,
      subtextLineHeight: 1.15,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Shop now",
      ctaShowIcon: true,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.05,
      imageOffsetX: 0,
      imageOffsetY: -10,
      headline: "Upgrade your next campaign",
      subtext: "A clean, premium look your brand system will love.",
    },
  },
  {
    id: "photo-band-on-band",
    title: "Photo + Band",
    description: "Classic photo on top with a text band below.",
    targetOrientations: ["landscape", "portrait", "square"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "bottom",
      photoBandHeightRatio: 0.53,
      photoBandCtaPlacement: "onBand",
      headlineFontScale: 1,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Learn more",
      ctaShowIcon: false,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.02,
      imageOffsetX: 0,
      imageOffsetY: -15,
      headline: "From idea to launch faster",
      subtext: "Put your message and brand details in the right place, every time.",
    },
  },
  {
    id: "photo-band-cta-on-photo",
    title: "CTA on Photo",
    description: "Main message in the band, button overlays the photo area.",
    targetOrientations: ["landscape", "portrait", "square"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "bottom",
      photoBandHeightRatio: 0.47,
      photoBandCtaPlacement: "onPhoto",
      headlineFontScale: 1,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "See the offer",
      ctaShowIcon: true,
      ctaAlign: "right",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.08,
      imageOffsetX: 0,
      imageOffsetY: -20,
      headline: "Turn attention into action",
      subtext: "Clean typography + brand-locked colors built for every size.",
    },
  },
  {
    id: "photo-band-top-on-band",
    title: "Band on Top (CTA in Band)",
    description: "Text band placed at the top with CTA inside the band.",
    targetOrientations: ["landscape", "portrait", "square"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "top",
      photoBandHeightRatio: 0.52,
      photoBandCtaPlacement: "onBand",
      headlineFontScale: 1,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Learn more",
      ctaShowIcon: false,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.03,
      imageOffsetX: 0,
      imageOffsetY: -14,
      headline: "More focus, more clarity",
      subtext: "A top band layout that keeps your message readable.",
    },
  },
  {
    id: "photo-band-top-on-photo",
    title: "Band on Top (CTA on Photo)",
    description: "Band on top with CTA overlaying the photo area for punchy emphasis.",
    targetOrientations: ["landscape", "portrait", "square"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "top",
      photoBandHeightRatio: 0.46,
      photoBandCtaPlacement: "onPhoto",
      headlineFontScale: 1,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Shop now",
      ctaShowIcon: true,
      ctaAlign: "right",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.1,
      imageOffsetX: 0,
      imageOffsetY: -20,
      headline: "Make your offer pop",
      subtext: "CTA overlay tuned for attention at a glance.",
    },
  },
  {
    id: "photo-band-leaderboard",
    title: "Leaderboard Boost",
    description: "Tight, fast message with the CTA in the band.",
    targetOrientations: ["landscape"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "leaderboard",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "left",
      photoBandHeightRatio: 0.43,
      photoBandCtaPlacement: "onBand",
      headlineFontScale: 0.95,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Shop now",
      ctaShowIcon: false,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.06,
      imageOffsetX: 0,
      imageOffsetY: -10,
      headline: "Limited-time deal",
      subtext: "Get more for less with brand-safe design.",
    },
  },
  {
    id: "photo-band-leaderboard-cta-on-photo",
    title: "Leaderboard CTA on Photo",
    description: "Same leaderboard split, but the button overlays the photo.",
    targetOrientations: ["landscape"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "leaderboard",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "left",
      photoBandHeightRatio: 0.43,
      photoBandCtaPlacement: "onPhoto",
      headlineFontScale: 0.95,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Shop now",
      ctaShowIcon: true,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.1,
      imageOffsetX: 0,
      imageOffsetY: -10,
      headline: "Limited-time deal",
      subtext: "CTA overlays the photo for faster attention.",
    },
  },
  {
    id: "photo-band-leaderboard-right-on-band",
    title: "Leaderboard Right Band",
    description: "Band on the right with the CTA living inside the band.",
    targetOrientations: ["landscape"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "leaderboard",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "right",
      photoBandHeightRatio: 0.43,
      photoBandCtaPlacement: "onBand",
      headlineFontScale: 0.95,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Get started",
      ctaShowIcon: false,
      ctaAlign: "right",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "right",
      imageScale: 1.06,
      imageOffsetX: 0,
      imageOffsetY: -10,
      headline: "A cleaner way to launch",
      subtext: "Right-band layout tuned for banners and leaderboards.",
    },
  },
  {
    id: "photo-band-left-on-photo",
    title: "Band Left, CTA On Photo",
    description: "Wide photo with a left band and a prominent CTA on the photo area.",
    targetOrientations: ["landscape"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "left",
      photoBandHeightRatio: 0.5,
      photoBandCtaPlacement: "onPhoto",
      headlineFontScale: 1,
      subtextFontScale: 1,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "See details",
      ctaShowIcon: true,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.12,
      imageOffsetX: -6,
      imageOffsetY: -18,
      headline: "More clarity, more conversions",
      subtext: "CTA placement tuned to keep attention where it matters.",
    },
  },
  {
    id: "photo-band-right-on-band",
    title: "Right Band, CTA In Band",
    description: "Right-positioned band with CTA living inside the band.",
    targetOrientations: ["landscape"],
    adLayout: AD_TEMPLATE_KIND.PHOTO_BAND,
    photoBandMode: "tall",
    patch: {
      adLayout: "photoBand",
      photoBandPosition: "right",
      photoBandHeightRatio: 0.56,
      photoBandCtaPlacement: "onBand",
      headlineFontScale: 0.98,
      subtextFontScale: 1.02,
      headlineAlign: "left",
      subtextAlign: "left",
      cta: "Get started",
      ctaShowIcon: false,
      ctaAlign: "left",
      logoPlacement: "inLayout",
      logoScale: 1,
      logoAlign: "left",
      imageScale: 1.06,
      imageOffsetX: 6,
      imageOffsetY: -12,
      headline: "Turn views into action",
      subtext: "A tight band layout that stays readable across sizes.",
    },
  },
];

export function getAdTemplatesFor({ orientation, adLayout, photoBandMode, isLeaderboardFormat }) {
  return AD_TEMPLATES.filter((t) => {
    if (t.adLayout !== adLayout) return false;
    const okOrientation = !t.targetOrientations || t.targetOrientations.includes(orientation);
    if (!okOrientation) return false;
    if (typeof t.targetIsLeaderboard === "boolean" && t.targetIsLeaderboard !== Boolean(isLeaderboardFormat)) {
      return false;
    }
    if (t.adLayout === AD_TEMPLATE_KIND.PHOTO_BAND) {
      if (t.photoBandMode === "any") return true;
      return t.photoBandMode === photoBandMode;
    }
    return true;
  });
}
