import colorPaletteShades from "brandsync-tokens/themebuilder.json";

export const productColors = [
  { name: "purple", src: "/accessible-palettes/purple.svg" },
  { name: "cobalt", src: "/accessible-palettes/cobalt.svg" },
  { name: "blue", src: "/accessible-palettes/blue.svg" },
  { name: "steel", src: "/accessible-palettes/steel.svg" },
  { name: "teal", src: "/accessible-palettes/teal.svg" },
  { name: "jade", src: "/accessible-palettes/jade.svg" },
  { name: "green", src: "/accessible-palettes/green.svg" },
  { name: "lime", src: "/accessible-palettes/lime.svg" },
  { name: "yellow", src: "/accessible-palettes/yellow.svg" },
  { name: "amber", src: "/accessible-palettes/amber.svg" },
  { name: "orange", src: "/accessible-palettes/orange.svg" },
  { name: "magenta", src: "/accessible-palettes/magenta.svg" },
  { name: "maroon", src: "/accessible-palettes/maroon.svg" },
  { name: "violet", src: "/accessible-palettes/violet.svg" },
];

export const exportTabs = [
  { label: "Primary", value: "palettes" },
  { label: "Semantics", value: "semantics" },
  { label: "Typography", value: "typography" },
  { label: "Example Pages", value: "preview" },
  { label: "Token Preview", value: "token-preview" },
];

export const formatTabs = [
  { label: "CSS", value: "css" },
  { label: "SCSS", value: "scss" },
  { label: "JSON", value: "json" },
  { label: "JS Const", value: "js" },
];

export const viewportTabs = [
  { label: "Desktop", value: "desktop" },
  { label: "Tablet", value: "tablet" },
  { label: "Mobile", value: "mobile" },
];

// Typography data based on the design system - responsive values for each viewport
export const typographyData = {
  desktop: {
    display: [
      {
        name: "Display 1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 80,
        lineHeight: 96,
        paragraphSpacing: 40,
      },
      {
        name: "Display 2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 72,
        lineHeight: 88,
        paragraphSpacing: 36,
      },
      {
        name: "Display 3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 60,
        lineHeight: 72,
        paragraphSpacing: 30,
      },
      {
        name: "Display 4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 56,
        lineHeight: 64,
        paragraphSpacing: 28,
      },
      {
        name: "Display 5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 48,
        lineHeight: 56,
        paragraphSpacing: 24,
      },
      {
        name: "Display 6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 40,
        lineHeight: 48,
        paragraphSpacing: 20,
      },
      {
        name: "Display 7",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
    ],
    headings: [
      {
        name: "h1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 48,
        lineHeight: 56,
        paragraphSpacing: 24,
      },
      {
        name: "h2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 40,
        lineHeight: 48,
        paragraphSpacing: 20,
      },
      {
        name: "h3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
      {
        name: "h4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 24,
        lineHeight: 32,
        paragraphSpacing: 12,
      },
      {
        name: "h5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 20,
        lineHeight: 24,
        paragraphSpacing: 10,
      },
      {
        name: "h6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 16,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    body: [
      {
        name: "lg-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "lg-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "lg-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "md-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "sm-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    caption: [
      {
        name: "lg",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
    ],
  },
  tablet: {
    display: [
      {
        name: "Display 1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 72,
        lineHeight: 88,
        paragraphSpacing: 36,
      },
      {
        name: "Display 2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 64,
        lineHeight: 72,
        paragraphSpacing: 32,
      },
      {
        name: "Display 3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 56,
        lineHeight: 64,
        paragraphSpacing: 28,
      },
      {
        name: "Display 4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 48,
        lineHeight: 56,
        paragraphSpacing: 24,
      },
      {
        name: "Display 5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 40,
        lineHeight: 48,
        paragraphSpacing: 20,
      },
      {
        name: "Display 6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
      {
        name: "Display 7",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 24,
        lineHeight: 32,
        paragraphSpacing: 12,
      },
    ],
    headings: [
      {
        name: "h1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 40,
        lineHeight: 48,
        paragraphSpacing: 20,
      },
      {
        name: "h2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
      {
        name: "h3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 24,
        lineHeight: 32,
        paragraphSpacing: 12,
      },
      {
        name: "h4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 22,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "h5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 20,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "h6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 16,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    body: [
      {
        name: "lg-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "lg-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "lg-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "md-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "sm-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    caption: [
      {
        name: "lg",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "md",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
    ],
  },
  mobile: {
    display: [
      {
        name: "Display 1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 64,
        lineHeight: 72,
        paragraphSpacing: 32,
      },
      {
        name: "Display 2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 56,
        lineHeight: 64,
        paragraphSpacing: 28,
      },
      {
        name: "Display 3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 48,
        lineHeight: 56,
        paragraphSpacing: 24,
      },
      {
        name: "Display 4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 40,
        lineHeight: 48,
        paragraphSpacing: 20,
      },
      {
        name: "Display 5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
      {
        name: "Display 6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 24,
        lineHeight: 32,
        paragraphSpacing: 12,
      },
      {
        name: "Display 7",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 20,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
    ],
    headings: [
      {
        name: "h1",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 32,
        lineHeight: 40,
        paragraphSpacing: 16,
      },
      {
        name: "h2",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 28,
        lineHeight: 36,
        paragraphSpacing: 12,
      },
      {
        name: "h3",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 24,
        lineHeight: 32,
        paragraphSpacing: 10,
      },
      {
        name: "h4",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 22,
        lineHeight: 28,
        paragraphSpacing: 10,
      },
      {
        name: "h5",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 20,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "h6",
        fontFamily: "Roboto",
        fontWeight: "Bold",
        fontSize: 16,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    body: [
      {
        name: "lg-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 18,
        lineHeight: 24,
        paragraphSpacing: 10,
      },
      {
        name: "lg-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 18,
        lineHeight: 24,
        paragraphSpacing: 10,
      },
      {
        name: "lg-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 18,
        lineHeight: 24,
        paragraphSpacing: 10,
      },
      {
        name: "md-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "md-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 16,
        lineHeight: 24,
        paragraphSpacing: 8,
      },
      {
        name: "sm-regular",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 12,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 12,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 12,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
    ],
    caption: [
      {
        name: "lg",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "md",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 14,
        lineHeight: 20,
        paragraphSpacing: 8,
      },
      {
        name: "sm",
        fontFamily: "Roboto",
        fontWeight: "Regular",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-medium",
        fontFamily: "Roboto",
        fontWeight: "Medium",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
      {
        name: "sm-semibold",
        fontFamily: "Roboto",
        fontWeight: "Semibold",
        fontSize: 12,
        lineHeight: 16,
        paragraphSpacing: 6,
      },
    ],
  },
};

export const getColorShades = (colorName) => {
  // Helper to create shade objects with both color and shade number
  const createShade = (shade, color = colorName) => ({
    color: colorPaletteShades[color].shades[shade],
    shade,
  });

  const tokenPreviewCategories = {
    primary: {
      description:
        "Your primary color is your product's main brand color. It's used for the most important actions on a screen, like primary buttons.",
      light: {
        default: createShade(600),
        hover: createShade(700),
        focused: createShade(700),
        pressed: createShade(800),
        container: createShade(50),
        "container-hover": createShade(100),
      },
      dark: {
        default: createShade(400),
        hover: createShade(300),
        focused: createShade(300),
        pressed: createShade(200),
        container: createShade(950),
        "container-hover": createShade(900),
      },
    },
    neutrals: {
      description:
        "Neutrals are the core colors used for surfaces, backgrounds, borders, and text. They create structure, provide contrast, and help your primary and accent colors stand out without competing for attention.",
      light: {
        default: createShade(700, "neutral"),
        hover: createShade(800, "neutral"),
        focused: createShade(800, "neutral"),
        pressed: createShade(900, "neutral"),
        container: createShade(50, "neutral"),
        "container-hover": createShade(100, "neutral"),
        "container-focused": createShade(200, "neutral"),
        "container-pressed": createShade(300, "neutral"),
      },
      dark: {
        default: createShade(300, "neutral"),
        hover: createShade(200, "neutral"),
        focused: createShade(200, "neutral"),
        pressed: createShade(50, "neutral"),
        container: createShade(900, "neutral"),
        "container-hover": createShade(800, "neutral"),
        "container-focused": createShade(800, "neutral"),
        "container-pressed": createShade(700, "neutral"),
      },
    },
    success: {
      description:
        "Used for positive actions or confirmations. It shows the user that something went right.",
      light: {
        default: createShade(600, "success"),
        hover: createShade(700, "success"),
        focused: createShade(700, "success"),
        pressed: createShade(800, "success"),
        container: createShade(100, "success"),
      },
      dark: {
        default: createShade(400, "success"),
        hover: createShade(300, "success"),
        focused: createShade(300, "success"),
        pressed: createShade(200, "success"),
        container: createShade(800, "success"),
      },
    },
    error: {
      description:
        "Used to highlight problems that need attention, such as invalid inputs, failed actions, or critical alerts. Error colors help users quickly identify what went wrong and how to fix it.",
      light: {
        default: createShade(600, "error"),
        hover: createShade(700, "error"),
        focused: createShade(700, "error"),
        pressed: createShade(800, "error"),
        container: createShade(100, "error"),
      },
      dark: {
        default: createShade(400, "error"),
        hover: createShade(300, "error"),
        focused: createShade(300, "error"),
        pressed: createShade(200, "error"),
        container: createShade(950, "error"),
      },
    },
    warning: {
      description:
        "Used for things that need attention but aren't critical. It helps users stay aware and take caution.",
      light: {
        default: createShade(600, "warning"),
        hover: createShade(700, "warning"),
        focused: createShade(700, "warning"),
        pressed: createShade(800, "warning"),
        container: createShade(100, "warning"),
      },
      dark: {
        default: createShade(400, "warning"),
        hover: createShade(300, "warning"),
        focused: createShade(300, "warning"),
        pressed: createShade(200, "warning"),
        container: createShade(800, "warning"),
      },
    },
    information: {
      description:
        "Used to share helpful, non-urgent messages, like general updates, notices, or contextual guidance. Information colors draw attention without creating a sense of warning or urgency.",
      light: {
        default: createShade(600, "information"),
        hover: createShade(700, "information"),
        focused: createShade(700, "information"),
        pressed: createShade(800, "information"),
        container: createShade(100, "information"),
      },
      dark: {
        default: createShade(400, "information"),
        hover: createShade(300, "information"),
        focused: createShade(300, "information"),
        pressed: createShade(200, "information"),
        container: createShade(800, "information"),
      },
    },
  };

  return tokenPreviewCategories;
};
